### ISSUE TITLE
1.9: Changes to the register process for Blocks, ItemBlock etc?

### ISSUE THREAD

**Issue by cemerson** [TheGreyGhost/MinecraftByExample#14]
This is a great resource you guys have setup here - props and thanks!

Any chance you'll be adding some updated things for 1.9? I'm especially stumped with how to deal with how you have to register Blocks and ItemBlocks separately and could use some help (or a point in the right direction).

Thanks and very nice work here again!

**Comment by TheGreyGhost** [comment]
Thanks for the comment, glad you found it useful... sorry for the slow reply, I missed it completely before now
I'm planning on updating to 1.9 soon - or skipping to 1.10 if Forge is stable, I have a couple of other things on the go.

Or, if you figure it out in the meantime, I'd be very grateful for pointers or code snippets :)

**Comment by TheGreyGhost** [comment]
Just for the record, have updated to 10.1.2 with the new registration.  Hopefully you had already figured it out by now :)
