### ISSUE TITLE
Why is there no .gitignore file?

### ISSUE THREAD

**Issue by TheStoneWolf** [TheGreyGhost/MinecraftByExample#16]
My deepest thanks to all of you for having created this! It is a big help in my minecraft modding endeavour! Though I must admitt that I am very surprised to see that you have no .gitignore file here. Isn't that a very important part of having your minecraft mod on Github? I have had many different suggestions on how I should go forward with the .gitignore file and I am unsure how to go forward...

I do know that having your mod on Github is by no means a requirement when it comes to modding but knowing how helpful I found looking at the mods here on Github I want to help others going through the same process.

All of your help would be deeply appreciated!

**Comment by phase** [comment]
`.gitignore` isn't a requirement for any project. For Java projects, they usually contain Eclipse and IntelliJ files. If you know how to `git add src`, then it isn't needed. [Something like this](https://www.gitignore.io/api/java%2Cintellij%2Ceclipse%2Cgradle) would work.

**Comment by TheGreyGhost** [comment]
You're welcome, glad you find it useful :)
Like Phase commented - I don't use  .gitignore because I manually specify the files that I want to add to version control (and manually remove the ones that I don't).  Just a personal preference really.  If you fork the project you can add one if you wish (or not).

**Comment by TheStoneWolf** [comment]
Oh...
Yeah, now I get it. Thanks for the help anyhow~ ^-^

**Comment by yooksi** [comment]
Was wondering the same. I think .gitignore would be a nice addition for other devs.
