### ISSUE TITLE
[Minor] Copper Texture has a slight model bug

### ISSUE THREAD

**Issue by Flamarow** [TheGreyGhost/MinecraftByExample#22]
The copper texture has a 3 pixels in the top right that are not fully transparent which causes you to see through the texture from the side when being rendered in minecraft when following the 1.10.2 tutorial.

Erasing those 3 pixels fixed the model issue pretty easily. I learned something about minecraft textures I didn't know so I'm a bit happy about this 'bug'. =P

**Comment by TheGreyGhost** [comment]
Keen, thanks for letting me know.
