### ISSUE TITLE
1.11.2 compatibility - mbe11_item_variants/ItemVariants.java

### ISSUE THREAD

**Issue by z9x** [TheGreyGhost/MinecraftByExample#24]
Just FYI - Testing with 1.11.2 beta build (13.20.0.2227) the method signature for getSubItems changed to be a NonNullList:
`  public void getSubItems(Item itemIn, CreativeTabs tab, NonNullList<ItemStack> subItems)`

Since this method does not currently have the `@Override` attribute, the build did not flag an error when I tried to build with1.11.2 - but the item variants did not show up in the creative inventory since getSubItems was not correctly overriden.

Recommend adding the `@Override` attribute, to force an error if someone tries to build with 1.11.2, at least until such time as you choose to update your code to 1.11.2?

**Comment by z9x** [comment]
Never mind - see you already updated in your 1.11 branch...

**Comment by TheGreyGhost** [comment]
Hi
Keen, thanks for the feedback.
Cheers  TGG
