### ISSUE TITLE
HUD overlay breaks creative mode

### ISSUE THREAD

**Issue by legodude17** [TheGreyGhost/MinecraftByExample#25]
When I put the HUD overlay item into my hotbar in creative, I no longer am able to access the create inventory.

**Comment by TheGreyGhost** [comment]
Hi
Yes, that's intentional - the modified HUD (health bar etc) only shows up in survival mode, not it in creative.  So when you put the HUD overlay item into your hotbar, it automatically shifts you out of creative mode into survival mode.
-TGG

**Comment by legodude17** [comment]
Ah, just bothers me because then I can't delete it from creative.
