### ISSUE TITLE
Camo block does not work on other camo blocks

### ISSUE THREAD

**Issue by mattparksjr** [TheGreyGhost/MinecraftByExample#26]
If you try to make a wall with the camo blocks, the camo block does not show the other camo block's disguise. For example. If i place 1 stone and place a camo block on that, it turns to stone. But if i add ANOTHER camo block on the one i placed, the default stone texture is placed....

**Comment by TheGreyGhost** [comment]
That's strange, it's not supposed to do that.  Thanks for letting me know.  I'll have a look- unfortunately it may take some time (weeks) due to other stuff taking up my time at the moment

**Comment by xXXIMMATTHEWXXx** [comment]
I think it has an issue with getting the block state of another camo block

**Comment by TheGreyGhost** [comment]
I tried to fix this in 1.15.2 and decided that doing a proper fix would detract from the purpose of the example, so I changed the intent i.e. camo blocks won't copy from adjacent camo blocks.
