### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by leo60228** [TheGreyGhost/MinecraftByExample#28]
The project's goal implies public domain, but I don't see a license.

**Comment by iamgreaser** [comment]
That's pretty much what I was thinking.

Without a licence it's All Rights Reserved by default.

If you want it to be in the public domain you can opt for CC0 which has a fallback for the countries which lack a concept of someone not owning something: https://creativecommons.org/publicdomain/zero/1.0/

**Comment by TheGreyGhost** [comment]
Thanks, I'll add a suitable statement about licensing.  The Unlicense looks good..
http://unlicense.org
