### ISSUE TITLE
[mbe15_item_dynamic_item_model] Generated BakeQuads don`t have correct normal int in vertexInt[]

### ISSUE THREAD

**Issue by rikka0w0** [TheGreyGhost/MinecraftByExample#33]
If you look carefully, you will find that the diamond block on the chess board is actually darker than what it is supposed to be. I use some of the code in that example, for block rendering is completely fine, but when it comes to item rendering, the model looks too dark. After read though the source code of Minecraft and Forge, I realize that the seventh int returned by vertexToInts() should not always be zero. That int represents an normal vector, but in packed form: ?? ZZ YY XX, it is used by OpenGL to calculate lighting.
See calculatePackedNormal() in [my code](https://github.com/rikka0w0/librikka/blob/master/src/rikka/librikka/model/quadbuilder/BakedQuadHelper.java) for some idea about how to calc that int value:

You just need to pass coordinate of all four vertexes to the function, be careful, don`t change the order of vertexes, otherwise the result is unpredictable!

**Comment by TheGreyGhost** [comment]
Hi  Keen, thanks for that, I will look into it.  I'm currently updating to 1.12 which is taking a long time, I will be sure to add your changes.  Cheers,  TGG

**Comment by TheGreyGhost** [comment]
Fixed it in 1.12.2, you were right!  Thanks for letting me know!
TGG
