### ISSUE TITLE
To many errors in 1.10.2 version

### ISSUE THREAD

**Issue by hohserg1** [TheGreyGhost/MinecraftByExample#35]
When I added the source from the 1.10.2 branch to my workspace, I found that there were a lot of errors in it.
For example, Minecraft#thePlayer is used instead of Minecraft#player, theWorld instead world.
In 1.11.2 there is no such branch.

**Comment by TheGreyGhost** [comment]
Hi
It sounds like you're using a different version of the MCP mappings.

Look in build.gradle for this section:
    // the mappings can be changed at any time, and must be in the following format.
    // snapshot_YYYYMMDD   snapshot are built nightly.
    // stable_#            stables are built at the discretion of the MCP team.
    // Use non-default mappings at your own risk. they may not allways work.
    // simply re-run your setup task after changing the mappings to update your workspace.
    mappings = "snapshot_20160518"

If your mappings doesn't match, you will get a lot of these errors.

Cheers
  TGG

**Comment by hohserg1** [comment]
I use stable_29, last version

**Comment by hohserg1** [comment]
Thank you, now I understand why so many mistakes
