### ISSUE TITLE
Suggestion: Convert Notes.txt to README.md

### ISSUE THREAD

**Issue by kylev** [TheGreyGhost/MinecraftByExample#41]
Changing from `.txt` to one of the [github-supported rich rendering formats](https://www.imdb.com/name/nm9506553/) like `.md` will make the notes easier to read and (probably) more pleasing to search engines. Furthermore, if you name the files `README.md`, github will auto-render it beneath the directory's file list as people browse the repo on the website.

I'd be willing to help with the conversion/formatting (as a pull request) if you approve a plan.

**Comment by TheGreyGhost** [comment]
Hi 
Thanks for the suggestion & the offer of help
The notes.txt is just a general notes for me, not really intended for mass consumption. 
Cheers
  TGG

**Comment by Boiethios** [comment]
Your `note.txt` are super useful for me as well! They are definitely more than a private reminder.

Thanks for all this work, by the way. Without it, it would be much more difficult to create a mod from scratch.

**Comment by TheGreyGhost** [comment]
Thanks mate, you're welcome :)
