### ISSUE TITLE
BlockRedstoneColouredLamp doesn't cope with redstone "just passing by"

### ISSUE THREAD

**Issue by harbaum** [TheGreyGhost/MinecraftByExample#48]
The BlockRedstoneColouredLamp works fine with any redstone that runs straight to the Lamp. Just like the ordinary RedstoneLamp. But redstone "passing by" visually connects to the lamp but in fact doesn't affect the lamp. Redstone "just passing by" also has no effect on regulat RedstoneLamps. But unlike BlockRedstoneColouredLamp they don't make the redstone attach to it visually in that case.

Imho the BlockRedstoneColouredLamp should not return true on canConnectRedstone at all. This way its visual representation would not wrongly suggest that it connects to passing redstone.

**Comment by harbaum** [comment]
![image](https://user-images.githubusercontent.com/9105084/50342075-baf21e00-0521-11e9-842f-a4302c07de7f.png)

**Comment by TheGreyGhost** [comment]
Hi Harbaum

Hmm that's odd, looks like there's something I misunderstood.  Thanks for letting me know.  I have very little time at the moment to spend on Minecraft modding, but when I do the next update for 13.2 (I hope in the next month!) I'll fix it then.

Cheers
  TGG

**Comment by TheGreyGhost** [comment]
Hi Harbaum
Well finally, 18 months later, I finally look at it.  You're right- although the IForgeBlock::canConnectRedstone says "for input and output", tracing through the code it's apparent that canConnectRedstone is strictly for output only.

I've fixed it, thanks for raising it :)

Cheers
  TGG
