### ISSUE TITLE
Pixel format not accelerated

### ISSUE THREAD

**Issue by Paulware** [TheGreyGhost/MinecraftByExample#53]
Thanks for putting this together...
This is the first time building/running the project...

With Windows 10, Getting this error: 

[11:59:28] [main/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Pixel format not accelerated

I can run normal Minecraft 1.12.2 on this computer.

Attached is entire console.
[console.txt](https://github.com/TheGreyGhost/MinecraftByExample/files/3237981/console.txt)
Thanks

**Comment by Paulware** [comment]
Tried this on another computer that had a graphics card and everything ran fine.

**Comment by RareScrap** [comment]
It is a common problem. Just update/install video driver.
