### ISSUE TITLE
Any plan for the 1.15.1 forge release?

### ISSUE THREAD

**Issue by rikka0w0** [TheGreyGhost/MinecraftByExample#54]

**Comment by TheGreyGhost** [comment]
Hi
Yeah I'm thinking about it; a lot going on for me in my non-coding life at the moment.  It depends how big the changes to 1.15 are; maybe I'll try a partial update to get an idea of how much work it will be.  It will be weeks or months not days though, unfortunately.

-TGG

**Comment by TheGreyGhost** [comment]
Have started updating to 1.15.2 now.

**Comment by rikka0w0** [comment]
Waiting for your goood news!
I was planning to upgrade my mod but encountered tooo much problem ---> The rendering part has changed a lot.

**Comment by TheGreyGhost** [comment]
Which things are you interested in?  I have updated the TileEntityRenderer so far, which shows a few different rendering techniques.

**Comment by rikka0w0** [comment]
I'm looking for the block renderering stuff, e.g. generating Bakedquads (or waht ever it is called now) by code.

**Comment by TheGreyGhost** [comment]
Ah ok.  I'll work on that one next, then.  I think it will still be relevant, I won't know until I start digging around.
