### ISSUE TITLE
Recipe JSON files are in the wrong spot for at least 1.15.2

### ISSUE THREAD

**Issue by xubiod** [TheGreyGhost/MinecraftByExample#56]
One thing I want to make clear: this is a great resource and it's extremely helpful for someone getting into modding. The only other version I've modded successfully is 1.7.10 and this is a great resource to get started on modern versions.

But back on track: recipe JSON files should be in `resources\data\modname\recipes`. At the moment, in the repository the folder is in the assets folder.

**Comment by TheGreyGhost** [comment]
Hi
Thanks for the positive feedback :)
Yeah you're right about the recipes in the wrong spot.  I haven't gotten around to updating that example yet, will do it next.
Cheers
 TGG

**Comment by TheGreyGhost** [comment]
All fixed...
