### ISSUE TITLE
Tutorial 01-1.12.2. Not picking lang name

### ISSUE THREAD

**Issue by Xaunther** [TheGreyGhost/MinecraftByExample#57]
Hello, and sorry if this is not the proper place to post this. I was following your nice tutorial to start on modded minecraft. I was able to complete the first task, except for the language file. I am following the example step by step, but I changed the names a bit so that I can learn better what's going on.

The thing is I am registering the simple block as 
```java
blockSimple =new BlockSimple();
blockSimple.setUnlocalizedName("xfbe01_block_simple");
blockSimple.setRegistryName("xfbe01_block_simple");
ForgeRegistries.BLOCKS.register(blockSimple);
// We also need to create and register an ItemBlock for this block otherwise it won't appear in the inventory
itemBlockSimple = new ItemBlock(blockSimple);
itemBlockSimple.setRegistryName(blockSimple.getRegistryName());
ForgeRegistries.ITEMS.register(itemBlockSimple);
```
So the corresponding lang file (en_US.lang) contains:
```
tile.xfbe01_block_simple.name=XFBE01 Block Simple
```

No errors appear when I run minecraft, it's simply that the displayed name of the block is tile.xfbe01_block_simple.name. 
I've checked that the language is set to english (US), I've tried with different names... I've tried in Linux and in Windows... but I never get to pick up the name provided in the lang file.

Do you have any idea on this? You can see my whole file structure at https://github.com/Xaunther/XauntherFBE. I just ran out of ideas to solve it...

Thanks!

**Comment by TheGreyGhost** [comment]
Howdy
I deleted the resources\pack.mcmeta file and it works properly now.
You could ask further questions in this forum
https://www.minecraftforge.net/forum/forum/70-modder-support/
Lots of helpful folks there who will usually reply a lot faster than I can

Cheers
  TGG

**Comment by Xaunther** [comment]
Owww, I guess when I copied that file I wasn't looking at the right branch...
Thank you very much for the solution and the advice!
