### ISSUE TITLE
Much of the example code is all commented out

### ISSUE THREAD

**Issue by simplebunsen** [TheGreyGhost/MinecraftByExample#59]
I found several cases where the code of an example is commented out entirely, like here https://github.com/TheGreyGhost/MinecraftByExample/blob/master/src/main/java/minecraftbyexample/mbe35_recipes/StartupCommon.java .
Why is that? It's hard to read without the proper colors ...

**Comment by TheGreyGhost** [comment]
Hi
It's commented out because I haven't converted that part to 1.15.2 yet.  Recipes are next after I finish the redstone.

Cheers
  TGG
