### ISSUE TITLE
[Question]Will you add Biomes and Dimensions

### ISSUE THREAD

**Issue by LG1somecoding** [TheGreyGhost/MinecraftByExample#61]

**Comment by LG1somecoding** [comment]
I forgot question mark.

**Comment by TheGreyGhost** [comment]
Howdy
Probably not in the near future; there are a few other things I want to add first.
-TGG

**Comment by Immortalin** [comment]
@LG1somecoding try https://github.com/UnRealDinnerbone/JAVD and https://github.com/UnRealDinnerbone/JAMD

They are both very short and very straightforward.

**Comment by TheGreyGhost** [comment]
Thanks Immortalin. I might add a reference to those at the next update.
