### ISSUE TITLE
[Error] Unexpected error 1.16.4

### ISSUE THREAD

**Issue by chrisvgt** [TheGreyGhost/MinecraftByExample#62]
I build your project and tested it with this`1.16.4-forge-35.1.0` Forge Version.
After a while i run in that Error `net.minecraftforge.fml.common.ObfuscationReflectionHelper$UnableToFindFieldException` caused by `java.lang.NoSuchFieldException: world`.

Does I miss something? Or is this version still in development?

The full [crash-log](https://pastebin.com/ExUU5BaS).

**Comment by TheGreyGhost** [comment]
Thanks for that, I'll have a look.

**Comment by TheGreyGhost** [comment]
It works fine for me, however I notice that your crash log has the obfuscated method names in it.  I think what is probably happening is related to obfuscation of the field name, i.e. the code is looking for "world" and it finds it fine when I'm running it but in your environment world is called something else such as field_200_a .  I'm not yet sure of the reason that it works fine for me but not for you; I'll try a couple of troubleshooting steps and will ask some other experts for advice.

**Comment by TheGreyGhost** [comment]
FYI: https://forums.minecraftforge.net/topic/94222-problems-with-inconsistent-deobfuscation-for-reflection-helper/

**Comment by TheGreyGhost** [comment]
Fixed now.  I should have used the srg name instead of mcp name.  I don't know why it worked for me but not for you, ("universal environment"?) but it appears to be ok now.  I also added some extra exception handling to make it more robust.
