### ISSUE TITLE
Mob creation and spawing? Can you point me in the right direction?

### ISSUE THREAD

**Issue by myxxmikeyxx** [TheGreyGhost/MinecraftByExample#63]
I am pretty sure you have this, I am just not sure what classes. I looked at Entities and Models and tried to look at those classes but I am a bit lost and now doubting if I am in the right spot. 

For reference I am new to this and trying to learn so I am sorry if I was in the right place just not understanding.

**Comment by TheGreyGhost** [comment]
Howdy
Probably the best place to ask these questions is here:
https://forums.minecraftforge.net/forum/70-modder-support/

Lots of very helpful folks who answer questions a lot faster than me..!

MBE doesn't have anything for mobs specifically, but spawning entities can be done as mbe81 (in the item code).

-TGG
